services:

  postgres-db:
    image: postgres:18
    ports:
      - 5432:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d parakeet" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    environment:
      - POSTGRES_DB=parakeet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - parakeet-net

volumes:
  postgres-db-volume:


networks:
  parakeet-net:
    name: parakeet-net
    driver: bridge